version: '3.2'

services:
  database_dev:
    build: ./database
    ports:
      - 5432:5432
  server_dev:
    image: node:carbon
    working_dir: /usr/src/app
    volumes:
      - type: bind
        source: ./server
        target: /usr/src/app
    ports:
      - 3000:3000
    command: ["npm", "start"]

