service: 
  name: survey-rewards-backend
  
  # TODO: add a KMS key and ensure the secret app key is encrypted:
  #  awsKmsKeyArn: arn:aws:kms:us-east-1:XXXXXX:key/some-hash

custom:
  stage: ${opt:stage, self:provider.stage}
  config: ${file(../config/${self:custom.stage}.yml)}
  dynamodb:
    start:
        migrate: true
  customDomain:
    domainName: api-${self:custom.stage}.surveyrewards.network
    basePath: ''
    stage: ${self:custom.stage}
    createRoute53Record: true
    
plugins:
  - serverless-domain-manager
  - serverless-dynamodb-local
  - serverless-offline # must be last

provider:
  name: aws
  stage: dev
  profile: survey
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 128
  timeout: 10

  environment:
    STAGE: ${self:custom.stage}
    STELLAR_NETWORK: ${self:custom.config.STELLAR_NETWORK}
    API_URL: ${self:custom.config.API_URL}
    CLIENT_URL: ${self:custom.config.CLIENT_URL}
    APP_STORE: ${self:custom.config.APP_STORE}
    APP_KEY: ${self:custom.config.APP_KEY} # TODO: ensure this is encrypted - set a KMS key
    FEE_NEW_SURVEY: ${self:custom.config.FEE_NEW_SURVEY}
    REWARD_COMPLETE_SURVEY: ${self:custom.config.REWARD_COMPLETE_SURVEY}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["SurveysDynamoDBTable", "Arn" ] }
        - { "Fn::GetAtt": ["ResultsDynamoDBTable", "Arn" ] }

functions:
  app:
    handler: build/index.app
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: '{proxy+}'
          method: any
          cors: true

resources:
  Resources:
    SurveysDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.stage}_surveys

    ResultsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.stage}_results
